parameters:
    app_article.entity.class:                        App\DemoBundle\Entity\Article

services:
#    app_demo.example:
#        class: %app_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
